language: node_js
node_js:
    - "0.12"
    - "0.11"
    - "0.10"
    - "0.8"
    - "0.6"
    - "iojs"
    - "iojs-v1.0.4" 
before_install:
    - sudo add-apt-repository ppa:vase/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq etcd
    - nohup etcd &